---
filters: {}
rules:
  preset-ja-technical-writing: true
  preset-ja-spacing: true
  prh:
    rulePaths:
      - prh.yml
    checkHeader: true
    checkLink: false
    checkEmphasis: true
    checkBlockQuote: false
