baseURL: 'https://histudy.jp/'
title: '姫路IT系勉強会'

defaultContentLanguage: 'ja'
languageCode: 'ja'
hasCJKLanguage: true

theme: binario

menu:
  main:
  - identifier: categories
    name: 開催履歴
    url: /categories/meeting-log/
    weight: -60

  - identifier: topic
    name: Topics
    url: /topic/
    weight: -40

  - identifier: about
    name: About
    url: /about/
    weight: -20

  - identifier: search
    name: Search
    url: /search
    weight: 0
  - identifier: links
    name: Links
    url: /links
    weight: 0

Params:
  dateFormat: "2006-01-02"
  Entry:
    meta:
      - date
  colorTheme: dark-green
  Social:
    github: 'histudy'
  customCSS:
    - "css/custom.css"
  mainMenuAlignment: "right"
