# CircleCI 2.0 configuration file
#
# Environment Variables
#
#  HOST_NAME
#  USER_NAME
#  HOST_DEPLOY_PATH
#  SSH_PORT (Optional)
#
version: 2.1
general:
  branches:
    only:
      - master

jobs:
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "3a:48:3b:f5:ec:fb:8d:7a:4c:62:b9:19:01:e7:b1:58"
      - run:
          name: Add known host
          command: ssh-keyscan $HOST_NAME >> ~/.ssh/known_hosts
      - run:
          name: install rsync
          command: sudo apt update && sudo apt install -y rsync
      - run:
          name: deploy by rsync
          command: rsync -ahvz --delete -e ssh ./public/
            $USER_NAME@$HOST_NAME:$HOST_DEPLOY_PATH
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
orbs:
  hugo: circleci/hugo@1.2.2
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: false
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build
